//! Remote access: the durable device key, pairing, and who a request came from.
//!
//! Everything in §7 describes a portal bound to loopback, and that stays the
//! default. This module is the opt-in case (§12): a bind address other than
//! loopback, behind a key generated by `claude-web pair` and held on the paired
//! device. There are no accounts and no authorization layer — a device is
//! either paired or it is nothing.
//!
//! The file on disk holds **the SHA-256 of the key and not the key**. 256 bits
//! from the OS random source is not brute-forceable, so a bare hash verifies it
//! and nothing a KDF adds would matter. What the hash buys is that the file is
//! not a working credential: an agent running as the same user that reads it
//! has read nothing it can use, which is the property §7's never-on-disk token
//! has and a raw key would have given away.

use std::io::IsTerminal;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::time::{Duration, Instant};

use anyhow::{Context, Result, bail};
use sha2::{Digest, Sha256};

/// `~/.claude-web/remote-key`.
///
/// Deliberately not `config.toml`: the Settings endpoint rewrites that file
/// wholesale through `Config::save`, so a secret there is one serialisation
/// change away from being silently dropped — and it would sit in a file the
/// frontend round-trips.
pub fn key_path() -> PathBuf {
    crate::config::state_dir().join("remote-key")
}

/// At most one re-read of the key file per second, so a wrong key cannot be
/// turned into a file-read amplifier (§12).
const REREAD_QUIET: Duration = Duration::from_secs(1);

/// The hash of the paired device key, cached in memory.
///
/// The server holds the hash rather than re-reading the file per request.
/// Requiring a restart to pick up a *new* one would be a poor trade — §10 puts
/// agents surviving server death out of scope, so restarting to pair a tablet
/// would end every agent mid-task — so a key that fails against the cached hash
/// causes one re-read, throttled, and a retry. A fresh pairing therefore takes
/// effect on the paired device's first request, with no watcher and no signal
/// handler.
pub struct RemoteKey {
    path: PathBuf,
    cache: Mutex<Cache>,
}

struct Cache {
    hash: Option<[u8; 32]>,
    /// When the file was last re-read on a failed match. `None` until the first.
    reread_at: Option<Instant>,
}

impl RemoteKey {
    /// Load the hash at `path`. `Ok(None)` when no device has been paired.
    pub fn load(path: &Path) -> Result<Option<Self>> {
        let Some(hash) = read_hash(path)? else {
            return Ok(None);
        };
        Ok(Some(Self {
            path: path.to_path_buf(),
            cache: Mutex::new(Cache {
                hash: Some(hash),
                reread_at: None,
            }),
        }))
    }

    /// Does `presented` hash to the key we are paired with?
    pub fn matches(&self, presented: &str) -> bool {
        self.matches_at(presented, Instant::now())
    }

    /// Pure core of [`RemoteKey::matches`], so the re-read throttle can be
    /// tested without sleeping.
    fn matches_at(&self, presented: &str, now: Instant) -> bool {
        let given = sha256(presented.as_bytes());
        let mut cache = self.cache.lock().unwrap_or_else(|e| e.into_inner());
        if cache
            .hash
            .is_some_and(|known| constant_time_eq(&known, &given))
        {
            return true;
        }
        // A miss is either a dead key or a pairing this process has not seen
        // yet. One re-read a second tells the two apart without letting a
        // wrong key drive the filesystem.
        if cache
            .reread_at
            .is_some_and(|last| now.duration_since(last) < REREAD_QUIET)
        {
            return false;
        }
        cache.reread_at = Some(now);
        match read_hash(&self.path) {
            Ok(hash) => {
                cache.hash = hash;
                hash.is_some_and(|known| constant_time_eq(&known, &given))
            }
            Err(err) => {
                // Keep serving the hash we have: a half-written file during a
                // re-pair must not unpair every device.
                tracing::warn!(?err, "could not re-read the paired device key");
                false
            }
        }
    }
}

impl std::fmt::Debug for RemoteKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Never let the hash reach a log through a derived Debug, as
        // `SessionToken` does not let the token.
        f.write_str("RemoteKey(<redacted>)")
    }
}

/// Read the stored hash. `Ok(None)` when the file does not exist.
fn read_hash(path: &Path) -> Result<Option<[u8; 32]>> {
    let text = match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => return Err(err).with_context(|| format!("reading {}", path.display())),
    };
    let hex = text.trim();
    let bytes = decode_hex(hex).with_context(|| {
        format!(
            "{} does not hold a key hash; run `claude-web pair` to make a new one",
            path.display()
        )
    })?;
    Ok(Some(bytes))
}

/// Generate a key, store its hash at `path`, and return the key itself.
///
/// The raw key exists only in this moment: there is no "add a device", only
/// "re-pair every device". For two or three devices that is a minute of
/// scanning, and it keeps the file from being a working credential.
pub fn generate(path: &Path) -> Result<String> {
    let mut bytes = [0u8; 32];
    if getrandom::fill(&mut bytes).is_err() {
        bail!("the operating system random source is unavailable");
    }
    let key: String = bytes.iter().map(|b| format!("{b:02x}")).collect();
    write_hash(path, &key)?;
    Ok(key)
}

/// Write the SHA-256 of `key` to `path`, mode 0600.
fn write_hash(path: &Path, key: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    let hash = sha256(key.as_bytes());
    let hex: String = hash.iter().map(|b| format!("{b:02x}")).collect();
    std::fs::write(path, format!("{hex}\n"))
        .with_context(|| format!("writing {}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
            .with_context(|| format!("securing {}", path.display()))?;
    }
    Ok(())
}

/// Delete the key file. `Ok(false)` when there was nothing to delete.
///
/// Because a non-loopback bind refuses to start without one, this is also the
/// switch that turns remote access off — the lost-phone procedure, in one
/// command.
pub fn unpair(path: &Path) -> Result<bool> {
    match std::fs::remove_file(path) {
        Ok(()) => Ok(true),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(err) => Err(err).with_context(|| format!("removing {}", path.display())),
    }
}

/// Generate a key and print the QR code that carries it.
///
/// Refuses to run without a terminal attached: the entire output is a secret.
/// The startup path in §7 can fall back to a 0600 file because the server has
/// to start however it was invoked; pairing is a deliberate interactive act
/// with no headless case worth serving, and a file variant would only create
/// another on-disk copy of a raw key this design takes trouble not to keep.
pub fn pair(path: &Path, base_url: &str) -> Result<()> {
    if !std::io::stdout().is_terminal() {
        bail!(
            "`claude-web pair` prints a secret and needs a terminal; run it in one \
             (its whole output is the key)"
        );
    }
    let key = generate(path)?;
    print!("{}", pairing_screen(base_url, &key, path)?);
    Ok(())
}

/// The URL a paired device is sent to.
///
/// **The key rides in the fragment**, not the query string: a fragment is never
/// sent to the server and never appears in a `Referer`. The page reads it on
/// load and clears it with `history.replaceState`, so it does not sit in
/// browser history either — the same handling `common.js` already gives `?t=`.
pub fn pairing_url(base_url: &str, key: &str) -> String {
    format!("{}/#k={}", base_url.trim_end_matches('/'), key)
}

/// Everything `pair` prints, as one string — pure, so it can be asserted on.
fn pairing_screen(base_url: &str, key: &str, path: &Path) -> Result<String> {
    let url = pairing_url(base_url, key);
    let qr = qr_block(&url)?;
    Ok(format!(
        "\nScan this with the device you want to pair:\n\n{qr}\n\
         Or open it by hand:\n\n    {url}\n\n\
         The key is in the part after `#`, which never reaches the server. It is\n\
         stored on the device and only its hash is kept here, in {}.\n\
         Running `pair` again replaces it everywhere; `claude-web unpair` turns\n\
         remote access off.\n\n",
        path.display()
    ))
}

/// A QR code as Unicode half-blocks.
///
/// The alternative — printing the URL and letting you type 64 hex characters
/// into a phone — is bad enough that it would be routed around by pasting the
/// key into a chat app, which is a worse outcome than the dependency.
fn qr_block(url: &str) -> Result<String> {
    use qrcode::QrCode;
    use qrcode::render::unicode;
    let code = QrCode::new(url.as_bytes()).context("encoding the pairing QR code")?;
    Ok(code.render::<unicode::Dense1x2>().quiet_zone(true).build())
}

/// Which client a control-plane request came from (§12).
///
/// §7 already writes a permission-mode change into the agent's event log with
/// its initiator. With two credential paths that field gains a meaning it did
/// not have on loopback: *which client*. Having given up per-device sessions,
/// that log is the only visibility into which devices are acting.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Initiator {
    /// A loopback client holding this run's per-boot token (§7).
    Local,
    /// A paired device, and the address it reached us from.
    Paired { peer: String },
}

impl Initiator {
    /// `local` or `paired`.
    pub fn channel(&self) -> &'static str {
        match self {
            Self::Local => "local",
            Self::Paired { .. } => "paired",
        }
    }

    pub fn peer(&self) -> Option<&str> {
        match self {
            Self::Local => None,
            Self::Paired { peer } => Some(peer),
        }
    }

    /// What goes into the agent's event log.
    pub fn label(&self) -> String {
        match self {
            Self::Local => "local".to_string(),
            Self::Paired { peer } => format!("paired {peer}"),
        }
    }
}

impl std::fmt::Display for Initiator {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.label())
    }
}

fn sha256(bytes: &[u8]) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher.finalize().into()
}

/// Compare without leaking the answer through timing, as `SessionToken` does.
fn constant_time_eq(a: &[u8; 32], b: &[u8; 32]) -> bool {
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

fn decode_hex(hex: &str) -> Result<[u8; 32]> {
    if hex.len() != 64 {
        bail!("expected 64 hex characters, found {}", hex.len());
    }
    let mut out = [0u8; 32];
    for (i, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16)
            .map_err(|_| anyhow::anyhow!("not hexadecimal"))?;
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_key_file_never_contains_the_key() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("remote-key");
        let key = generate(&path).expect("generate");
        assert_eq!(key.len(), 64, "256 bits, hex");

        let stored = std::fs::read_to_string(&path).expect("read");
        assert!(
            !stored.contains(&key),
            "the raw key must never be written to disk"
        );
        assert_eq!(stored.trim().len(), 64, "a bare SHA-256, hex");
        assert_ne!(stored.trim(), key);

        // And it is not world-readable.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).expect("stat").permissions().mode();
            assert_eq!(mode & 0o077, 0, "mode must be 0600, found {mode:o}");
        }
    }

    #[test]
    fn a_key_verifies_against_its_stored_hash() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("remote-key");
        let key = generate(&path).expect("generate");
        let remote = RemoteKey::load(&path).expect("load").expect("paired");
        assert!(remote.matches(&key));
        assert!(!remote.matches(""));
        assert!(!remote.matches(&key[..63]));
        assert!(!remote.matches(&format!("{key}x")));
        assert!(!remote.matches(&"a".repeat(64)));
    }

    #[test]
    fn no_key_file_means_no_pairing() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("remote-key");
        assert!(RemoteKey::load(&path).expect("load").is_none());
        assert!(!unpair(&path).expect("unpair"));
        generate(&path).expect("generate");
        assert!(unpair(&path).expect("unpair"));
        assert!(RemoteKey::load(&path).expect("load").is_none());
    }

    #[test]
    fn a_fresh_pairing_is_picked_up_without_a_restart() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("remote-key");
        let first = generate(&path).expect("generate");
        let remote = RemoteKey::load(&path).expect("load").expect("paired");
        assert!(remote.matches(&first));

        // `pair` runs again on the machine while the server keeps serving.
        let second = generate(&path).expect("re-pair");
        let t0 = Instant::now();
        assert!(
            remote.matches_at(&second, t0),
            "the new key must work on its first request"
        );
        assert!(
            !remote.matches_at(&first, t0 + REREAD_QUIET * 2),
            "the old key is dead immediately"
        );
    }

    #[test]
    fn a_wrong_key_cannot_be_turned_into_a_file_read_amplifier() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("remote-key");
        let key = generate(&path).expect("generate");
        let remote = RemoteKey::load(&path).expect("load").expect("paired");

        let t0 = Instant::now();
        assert!(!remote.matches_at(&"b".repeat(64), t0));
        // The file changes, but the throttle holds inside the window: the
        // second guess does not get to re-read it.
        let fresh = generate(&path).expect("re-pair");
        assert!(!remote.matches_at(&fresh, t0 + Duration::from_millis(500)));
        // Past the window it is read again.
        assert!(remote.matches_at(&fresh, t0 + REREAD_QUIET + Duration::from_millis(1)));
        assert!(!remote.matches(&key), "and the old key stays dead");
    }

    #[test]
    fn a_corrupt_key_file_is_refused_rather_than_ignored() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("remote-key");
        std::fs::write(&path, "not a hash\n").expect("write");
        let err = RemoteKey::load(&path).expect_err("must be refused");
        assert!(format!("{err:#}").contains("claude-web pair"), "{err:#}");
    }

    #[test]
    fn the_pairing_url_carries_the_key_in_the_fragment() {
        let url = pairing_url("http://100.64.0.7:7717/", "abc123");
        assert_eq!(url, "http://100.64.0.7:7717/#k=abc123");
        assert!(!url.contains('?'), "a query string would reach the server");

        let dir = tempfile::tempdir().expect("tempdir");
        let screen = pairing_screen("http://phone.tailnet:7717", "abc123", &dir.path().join("k"))
            .expect("screen");
        assert!(screen.contains("#k=abc123"), "{screen}");
        // The QR itself is drawn in half-blocks.
        assert!(screen.contains('▄') || screen.contains('█'), "{screen}");
    }

    #[test]
    fn an_initiator_names_the_channel_and_the_peer() {
        assert_eq!(Initiator::Local.channel(), "local");
        assert_eq!(Initiator::Local.label(), "local");
        assert_eq!(Initiator::Local.peer(), None);
        let paired = Initiator::Paired {
            peer: "100.64.0.7".to_string(),
        };
        assert_eq!(paired.channel(), "paired");
        assert_eq!(paired.peer(), Some("100.64.0.7"));
        assert_eq!(paired.label(), "paired 100.64.0.7");
    }

    #[test]
    fn sha256_matches_the_published_vectors() {
        let hex = |b: [u8; 32]| -> String { b.iter().map(|x| format!("{x:02x}")).collect() };
        assert_eq!(
            hex(sha256(b"abc")),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            hex(sha256(b"")),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
    }
}
